version: "3.8"

services:
  operator:
    image: rbelem/polymesh:latest
    env_file:
      - ./env.operator
    volumes:
      - operator:/var/lib/polymesh
    ports:
      - 30333:30333 # default libp2p port
      - 9615:9615   # prometheus exporter port
      - 9933:9933   # jsonrpc port
      - 9944:9944   # websocket rpc port
    networks:
      - operator
    ulimits:
      nofile:
        hard: 10240
        soft: 1024
    healthcheck:
      test:
        - "CMD"
        - "echo"
        - ">"
        - "/dev/tcp/127.0.0.1/9944"
        - "&&"
        - "echo"
        - ">"
        - "/dev/tcp/127.0.0.1/9615"
      interval: 10s
      start_period: 120s
      timeout: 5s
      retries: 6
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
  sentry:
    image: rbelem/polymesh:latest
    env_file:
      - ./env.sentry
    volumes:
      - sentry:/var/lib/polymesh
    ports:
      - 30333:30333 # default libp2p port
      - 9615:9615   # prometheus exporter port
      - 9933:9933   # jsonrpc port
      - 9944:9944   # websocket rpc port
    networks:
      - sentry
    ulimits:
      nofile:
        hard: 10240
        soft: 1024
    healthcheck:
      test:
        - "CMD"
        - "echo"
        - ">"
        - "/dev/tcp/127.0.0.1/9944"
        - "&&"
        - "echo"
        - ">"
        - "/dev/tcp/127.0.0.1/9615"
      interval: 10s
      start_period: 120s
      timeout: 5s
      retries: 6
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any

networks:
  operator:
  sentry:

volumes:
  operator:
  sentry:
